service: serverless-parameter-store

custom:
  settings:
    SECRET_VALUE: ${ssm:serverless-parameter-store-secret-value}

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: eu-west-1
  environment: ${self:custom.settings}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
