service: middy-parameter-test

provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters*
      Resource: arn:aws:ssm:us-east-1:*:parameter/middy-test/value1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
